[package]
name = "examples"
version = "0.1.0"
edition = "2024"
publish = false

[dev-dependencies]
helium = { path = "../helium", features = ["icon-sets"]}

[[example]]
name = "rect"
path = "rect.rs"


[[example]]
name = "hstack"
path = "hstack.rs"

