[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
helium = { path = "../helium" }
env_logger = "0.11.5"
log = "0.4.22"

[[example]]
name = "counter"
path = "counter.rs"
