[package]
name = "helium_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
wgpu = "22.1.0"
winit = { version = "0.29", features = ["rwh_05"] }
bytemuck = { version = "1.16", features = [ "derive" ] }

