[package]
name = "agape"
readme = "../README.md"
description = "A GUI library"
repository.workspace = true
keywords.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
image.workspace = true
thiserror.workspace = true
winit.workspace = true
log.workspace = true
fontdue = "0.9.3"
agape_core = {version = "0.1.0",path = "../agape_core"}
agape_macros = {version = "0.1.0",path = "../agape_macros"}
agape_layout = {version = "0.1.0",path = "../agape_layout"}
reqwest = {version = "0.12.12",features = ["blocking","stream","json"]}
tiny-skia.workspace = true
pixels.workspace = true